name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    uses: Corsinvest/.github/.github/workflows/cv4pve-tools-publish.yml@main
    secrets:
      WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
    with:
      project-name: cv4pve-vdi
      project-path: src/Corsinvest.ProxmoxVE.Vdi/Corsinvest.ProxmoxVE.Vdi.csproj
